//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinegest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilhete
    {
        public int Id { get; set; }
        public int Lugar { get; set; }
        public string Estado { get; set; }
        public int SessaoId { get; set; }
        public int FuncionarioId { get; set; }
        public int ClienteId { get; set; }
    
        public virtual Cliente Pessoas_Cliente { get; set; }
        public virtual Funcionario Pessoas_Funcionario { get; set; }
        public virtual Sessao Sessao { get; set; }
    }
}
