//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinegest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CineGestEntities : DbContext
    {
        public CineGestEntities()
            : base("name=CineGestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bilhete> Bilhetes { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Cinema> Cinemas { get; set; }
        public virtual DbSet<Filme> Filmes { get; set; }
        public virtual DbSet<Pessoa> Pessoas { get; set; }
        public virtual DbSet<Pessoas_Cliente> Pessoas_Cliente { get; set; }
        public virtual DbSet<Pessoas_Funcionario> Pessoas_Funcionario { get; set; }
        public virtual DbSet<Sala> Salas { get; set; }
        public virtual DbSet<Sessão> Sessão { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
