//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinegest
{
    using Cinegest.Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CineGestEntities : DbContext
    {
        public CineGestEntities()
            : base("name=CineGestEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {

            modelBuilder.Conventions.Remove<IncludeMetadataConvention>();
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bilhetes> Bilhetes { get; set; }
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<Cinemas> Cinemas { get; set; }
        public virtual DbSet<Filmes> Filmes { get; set; }
        public virtual DbSet<Pessoas> Pessoas { get; set; }
        public virtual DbSet<Pessoas_Cliente> Pessoas_Cliente { get; set; }
        public virtual DbSet<Pessoas_Funcionario> Pessoas_Funcionario { get; set; }
        public virtual DbSet<Salas> Salas { get; set; }
        public virtual DbSet<Sessão> Sessão { get; set; }
    }
}
