//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinegest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sala
    {
        public int Id { get; set; }
        public int Colunas { get; set; }
        public int Filas { get; set; }
        public int CinemaId { get; set; }
        public string Nome { get; set; }
    
        public virtual Cinema Cinema { get; set; }
    }
}
